---
title: "Course lectures for Biol 520C: Statistical modelling for biological data"
output: html_document
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Lecture slides and recordings for Biol 520C: Statistical modelling for biological data, 2023.

<br />

***
# Background and Simple Linear Regression
***
<br />

#### Lecture 01 - Course Intro

<a href="Lectures/Course_Intro.pdf" target="_blank">Slides.</a>

<a href="https://ubc.zoom.us/rec/share/08AoqO1QiyE-6nJNUo6zVg6Qu4d55fYClNpVOvMLyv_e0KHvAa2DX0nc5Bu1Ap3c.j1ofp1GZoXRK4DOO" target="_blank">Recording - 2024.</a>

<a href="https://ubc.zoom.us/rec/share/LhYPK9kO0J2msQ_o4AOuCYj5Uqlmj58nvCn0BiRGaRI1ZD1SOcEG3Dyu3aBNuJA6.Ub0iqzTk___JOq76" target="_blank">Recording - 2023.</a>

#### Lecture 02 - Simple Linear Regression

<a href="Lectures/02_Regression.pdf" target="_blank">Slides.</a>

<a href="https://ubc.zoom.us/rec/share/upK1SbC0VlG4RVpSu-VjCsHQrmj3zA-y8-bDbSbTZtdL7pMTbx2CHGJjlLSSKJGl.t5zaGXXwnBCwAfVt" target="_blank">Recording - 2024.</a>

<a href="https://ubc.zoom.us/rec/share/bFo0zeOrw1kNqdHZz7cthoyeez1Iv1eqRpomtTQEn2HbechNlTCkIAH_zOAXuqXG.kq-f3DNJrsgDUlIQ?startTime=1673625942000" target="_blank">Recording - 2023.</a>

#### Lecture 03 - Probability

<a href="Lectures/03_Probability.pdf" target="_blank">Slides.</a>

<a href="https://ubc.zoom.us/rec/share/x0et1cQXeQWlBmgiBdepHxj2uWW8T1VsbPYuQhgTsnrFKjBREu-noxyA9cyxhOty.32mvJ4I7nfgoI6IJ" target="_blank">Recording - 2024.</a>

<a href="https://ubc.zoom.us/rec/share/HJqt-WkM4sQnfR79YrWxfxNoZO9_GpWQnSu1G73yc7JvoCHOeaYaQrta16eLxkHU.nbpvWrU5avB-dQXz" target="_blank">Recording - 2023.</a>


#### Lecture 04 - Likelihood

<a href="Lectures/04_Likelihood.pdf" target="_blank">Slides. </a>

<a href="https://ubc.zoom.us/rec/share/T8NXeQ8sgd0-wC4HrmWMvhvevorZFJAmB73EqyOp6e-6k6kQBYb7fZltqJ9eFHww.Wf4E-pV9djzNZXpD" target="_blank">Recording - 2024.</a>

<a href="https://ubc.zoom.us/rec/share/XuV_dXMZ38hwfNr06jNqP3Io8PAW76J2Cbxqi0vxQIWz700QwvvnFON4UQL0Bi47.q8FpHpXRReF4-Hyt" target="_blank">Recording - 2023.</a>


***
# Mulitple Linear Regression
***

#### Lecture 05 - Mulitple Linear Regression

<a href="Lectures/05_Multiple_Linear_Regression.pdf" target="_blank">Slides. </a>

<a href="https://ubc.zoom.us/rec/share/CrK0Za8bLB0ITZL0XlFDKBcPzfIo-aSm5yCj8wj4qpVmFfAlqYAbujX5TIbb8Fjl.n6uLbU-1apWLg6rE" target="_blank">Recording - 2024.</a>

<a href="https://ubc.zoom.us/rec/share/aXsD4vfEv-I8RGgnECHoIh-pvy_niveq2YquHuMaphZIozSMSPc7AYTHQ6EAMV5-.jkxdJtyeTWbVJNSA" target="_blank">Recording - 2023.</a>

#### Lecture 06 - Interpreting Residuals

<a href="Lectures/06_Residuals.pdf" target="_blank">Slides. </a>

<a href="https://ubc.zoom.us/rec/share/k5KgDaSs8obAxt6pCm8sb-seqrqVmGfhWvuq3PoMqQ2kAITKAr2bYGwAKDoJgM3U.Z0p_OHVyUmjt7xJ6" target="_blank">Recording - 2024.</a>

<a href="https://ubc.zoom.us/rec/share/vEduJeGqKx6H-ZOW4RwzPop92Mhkmx5JO7EpwyOvaKpJ-u8-vPmcU01Ll7MQXsYw.zYMcWrFgF_960Q8m" target="_blank">Recording - 2023.</a>


#### Lecture 07 - Mixed Effects Models

<a href="Lectures/07_Mixed_Models.pdf" target="_blank">Slides. </a>

<a href="https://ubc.zoom.us/rec/share/m4wkZJoUxftCtobAI_mU7uvzhIIpobShuq7W3CUPtCEuIYy-fCquMK9_sTpSQUy_.MYQ0xYm47YpZotzr" target="_blank">Recording - 2022 (There was a technical issue in 2023).</a> 


#### Lecture 08 - Model Selection

<a href="Lectures/08_Model_Selection.pdf" target="_blank">Slides. </a>

<a href="https://ubc.zoom.us/rec/share/ZoZkugUOxgGHFXWhwFwyOhcDyRlDL7Fze5uefyIO_8uS6eGyCTZNVKG4dli1GCV_.wY7-waxZtf81i7Wp" target="_blank">Recording - 2023.</a>

#### Lecture 09 - Model Selection and Model Averaging

<a href="Lectures/09_Model_Averaging.pdf" target="_blank">Slides. </a>

<a href="https://ubc.zoom.us/rec/share/bJPhLers-004vw2H0Itk1gtmvy-2hvDDOafFGBRqXJ7dbCARj5UR4pqeYEnz2gSO.Uo6Jiri-QPu6J4Ca" target="_blank">Recording - 2023.</a>

<br />

***
# Breaking the IID Assumption
***

<br />

#### Lecture 10 Dealing with Heteroskedasticity

<a href="Lectures/10_Heteroscedasticity.pdf" target="_blank">Slides. </a>

<a href="https://ubc.zoom.us/rec/share/YDIEtUiXpzuN9AU0lMN487C9jC3-jQex95vKBFAC4aUwt9jdc2ydALH0rj6vSI55.6ZAnCkUwQPquLdvy?startTime=1676045128000" target="_blank">Recording - 2023.</a>

#### Lecture 11 Autocorrelation 1: Temporal Autocorrelation

<a href="Lectures/11_Autocorrelation_1.pdf" target="_blank">Slides. </a>

<a href="https://ubc.zoom.us/rec/share/EcyI5lYNSfFi6v0mgxHyOliGCjbG-IDPB-omP4KOIqvMGIYZCRvhGab7V_NxX-nD.yXorLt_j5_xmDd2z?startTime=1676477167000" target="_blank">Recording - 2023.</a>

#### Lecture 12 Autocorrelation 2: Spatial Autocorrelation

<a href="Lectures/12_Autocorrelation_2.pdf" target="_blank">Slides. </a>

<a href="https://ubc.zoom.us/rec/share/x1mSUUTy644GF3jhJTTm8ewmV1m1Q0nvscAVPk6eKCvfWOkovhd86ARqfIPlBqKg.1gbg5vvPDw_IJAtP?startTime=1676649882000" target="_blank">Recording - 2023.</a>

#### Lecture 13 Autocorrelation 3: Phylogenetic Autocorrelation

<a href="Lectures/13_Autocorrelation_3.pdf" target="_blank">Slides. </a>

<a href="https://ubc.zoom.us/rec/share/0NsYixXNGMb3xBKtTCwEpS5jb57Y1bgQrFCIpUn1mPFISxs-mxLWouLx9av05cmv.MAs7d21er4RhUqqn?startTime=1677859471000" target="_blank">Recording - 2023.</a>

<br />

***
# Breaking the Gaussian Assumption
***

<br />

<a href="Lectures/14_GLMs_1.pdf" target="_blank">Lecture 14 Generalised Linear Models 1: Intro to GLMs and Modelling Count Data </a>

<a href="Lectures/15_GLMs_2.pdf" target="_blank">Lecture 15 Generalised Linear Models 2: Modelling Binary and Proportional Data </a>

<br />

***
# Non-linearity and Stochastic Simulation
***

<br />

<a href="Lectures/16_Stochastic_Simulation.pdf" target="_blank">Lecture 16 Stochastic Simulation and Power Analysis </a>

<a href="Lectures/17_NonLinearity.pdf" target="_blank">Lecture 17 Deterministic functions for Modelling Biological Data </a>

