---
title: "Datasets for practicals"
output: html_document
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This page contains the datasets needed to complete the practicals for this course. To download, left click on the links and download the files as needed.

</br>

### Practical 02 - Deterministic models, stochastic models, simple linear regression, and maximum likelihood

<a href="Practical_Datasets/Musteloid_Data.csv" >Musteloid traits</a>

<a href="Practical_Datasets/Wasp_Choice.csv" >Wasp choice.</a>

</br>

### Practical 03 - Multiple linear regression and model residuals

<a href="Practical_Datasets/Seedling.csv" >Seedlings.</a>

<a href="Practical_Datasets/Ismail.csv" >Forest degredation.</a>

</br>

### Practical 04 - Visualising Nested Data Prior to Analysis

<a href="Practical_Datasets/Owls.csv" >Owl begging behaviour</a>

</br>

### Practical 05 - Mixed Effect Models, Model Selection, and Model Averaging

<a href="Practical_Datasets/Owls.csv" >Owl begging behaviour</a>

</br>

### Practical 06 - Heteroskedasticity, Temporal Autocorrelation, and the IID Assumption

<a href="Practical_Datasets/Cod_daily_depth_data.csv" >Cod depths</a>

</br>

### Practical 07 - Spatial and Phylogenetic Autocorrelation

<a href="Practical_Datasets/SDI2003.csv" >SDI and pH</a>

<a href="Practical_Datasets/rockfish.csv" >Rockfish traits</a>

<a href="Practical_Datasets/rockfish.phy.txt" >Rockfish phylogenetic tree</a>

</br>

### Practical 09 - Logistic Regression: Generalised Linear Models for 0,1 and Proportion Data

<a href="Practical_Datasets/gophertortoise.csv" >Gopher tortoise infection status</a>

</br>

### Practical 10 - Stochastic Simulation, Power Analysis, and Non-Linear Models

<a href="Practical_Datasets/Seedling.csv" >Seedlings</a>

<a href="Practical_Datasets/jaw_bone.csv" >Deer jaw bones</a>

<a href="Practical_Datasets/Wild_Boar.csv" >Wild boar Tb</a>
